spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: pedido.exchange  # Adicione esta linha para configurar a exchange padrão

app:
  rabbitmq:
    queues:
      criado: pedido.criado.queue  # Nome da fila como variável de configuração
      deletado: pedido.deletado.queue

pagamento-service:
  base-url: http:localhost:8092/pagamento

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    com.tcc.pedido_service: DEBUG